import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { getServerSession } from "next-auth/next";
import { authOptions } from "@/app/api/auth/[...nextauth]/route";
import SignOutButton from "@/components/SignOutButton";
import { SessionProvider } from "next-auth/react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const session = await getServerSession(authOptions);

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-[#E7E2FF]`}
      >
        {/* Navbar */}
        <div className="flex justify-between items-center bg-white p-3 rounded-2xl w-[90%] mx-auto mt-4 shadow-md">
          <div>
            <Link
              href="/"
              className="font-bold text-purple-700 hover:text-purple-900"
            >
              Home
            </Link>
          </div>

          <div>
            {session?.user ? (
              <div className="flex items-center gap-3">
                <span className="font-bold text-purple-700">
                  {session.user.name}
                </span>
                <Link
                  href="/my-project"
                  className="text-purple-700 font-semibold hover:text-purple-900 transition-colors"
                >
                  My Project
                </Link>
                <SignOutButton />
              </div>
            ) : (
              <div className="flex gap-3 items-center">
                <Link
                  href="/sign-up"
                  className="text-purple-700 font-semibold px-4 py-2 rounded-2xl hover:text-purple-900 transition-colors"
                >
                  Sign Up
                </Link>
                <Link
                  href="/sign-in"
                  className="bg-[#E7E2FF] px-4 py-2 rounded-2xl font-semibold hover:bg-purple-200 transition-colors "
                >
                  Sign In
                </Link>
              </div>
            )}
          </div>
        </div>
        {children}
      </body>
    </html>
  );
}
